### PR TITLE
Docker build for backend

### PR DESCRIPTION
**Pull request by WardToulet**
This is a simple version of a dockerized build for the backend services that can be easily recreated on a new system.

It's currently WIP but I crated a pull request to check with others if this structure is workable.

Future edits would mainly contain live reloading.

### CODE REVIEW

**Comment by SimonBackx** [comment]
A next step could be to also incorporate Caddy or NGINX into Docker. The Docker container can then expose only port 80. Only the DNS things (hosts file or local DNS server) and (maybe) building of the frontend would remain outside Docker.

We use Caddy in production because we need to automatically generate certificates for a lot of domains. Running certbot manually would be a struggle, certainly in combination with needing to reload NGINX. For now very happy with the, also more logically structures configs. But in development, without SSL, we can use both (or Apache even).

**Comment by WardToulet** [comment]
I am currently working on adding the proxy into the docker-compose but this is a bit difficult as the caddy files are in the root of the project, would you be opposed to moving them into their own folder in this way it would be easy to mount them into the caddy container that runs the reverse proxy this should also de-clutter the root folder.

**Comment by WardToulet** [comment]
The reverse proxy setup in docker is done. I will update it's config as I add more of the services to the docker build.

It uses a custom docker images based on the official caddy docker image but overriding the start command as to keep using json for the configuration. 

Future improvements may be:
- [ ] re add the the proxy for the sgv endpoints
- [ ] allow ssl on local with self-signed certificate (not sure if this is very useful)
- [ ] proxy the fronted (propably will not be using a wesberver for this in development to make use of the live reloading abillity of vue applications in development)

**Comment by WardToulet** [comment]
Problems running migrations. A problem occurs when trying to run the migrations. My first approach was to try using multi step builds in docker this doesn't work as only the top level cmd is executed in the container. There are two proposed solutions to this problem.
- Include the migration step in index.js
- Doe the migrations in another docker container

**Comment by WardToulet** [comment]
An error occurs when running the migrations, I've opened an issue #64 this is probably due to the version used of mysql used in the docker container. 

I wil try to update the db container to use a later version of mysql.

**Comment by WardToulet** [comment]
All the migrations and db stuff now work as intended, i am debating whether to include the phpmyadim route in the proxy as this is not to be expected on a deployed route but can be very useful for debugging and maybe a bit weird if it is using a port of localhost and all the other stamhoofd stuff is running behind the proxy.

**Comment by SimonBackx** [comment]
I would not include PhpMyAdmin, wouldn't that make it a bit bloated (and you need to include PHP etc). I think you better expose port 3306 (or a different one) and use a client on your own computer.

**Comment by WardToulet** [comment]
I will drop the phpmyadmin container from the docker-compose config. 
And maybe include instructions to add it yourself if you wish to use it.

Port 3306 is already exposed to the outisde so using external tools shouldn't be a problem (: .

**Comment by WardToulet** [comment]
This pull request is a bit stale at the moment because I'm working on routing, the final thing I would like to add is the live reloading of the code (using ts-node and a mounted volume) but I'm not shure if this would be viable with the builtime and such.

**Comment by WardToulet** [comment]
This pull request is a bit stale at the moment because I'm working on routing, the final thing I would like to add is the live reloading of the code (using ts-node and a mounted volume) but I'm not shore if this would be viable with the builtime and such.

**Comment by SimonBackx** [comment]
No problem! Just put it out of draft when you are ready.

I don't recomend using ts-node. I used it at the beginning of the project, but is it not usable in production (because more complicated and error prone deployment), and you get a difference between production and development builds. It also caused a lot of unexpected issues as I remember it correctly. The most issues are with the use of different file locations (running in dist vs running in src folder).

**Comment by SimonBackx** [comment]
Hi Ward, I'm temporarily closing your PR until you're ready to continue working on it ;)

**Pull request closed without merging**
